// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC593pQKjcrxY6wJbEe95LOwvrgGp0v4tU',
    appId: '1:27538477845:web:31818a678014923a414f1c',
    messagingSenderId: '27538477845',
    projectId: 'barber-booking-app-2ad2b',
    authDomain: 'barber-booking-app-2ad2b.firebaseapp.com',
    storageBucket: 'barber-booking-app-2ad2b.firebasestorage.app',
    measurementId: 'G-E5X0LL66S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCr-ozLfE-U8dUTcCGt8uTrkBtxafZOS4',
    appId: '1:27538477845:android:7c5c766f20e38675414f1c',
    messagingSenderId: '27538477845',
    projectId: 'barber-booking-app-2ad2b',
    storageBucket: 'barber-booking-app-2ad2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr6_DFqjw4St_px4MnKmgxWb7_LLH2vNE',
    appId: '1:27538477845:ios:dd4f2e2df6bc34d5414f1c',
    messagingSenderId: '27538477845',
    projectId: 'barber-booking-app-2ad2b',
    storageBucket: 'barber-booking-app-2ad2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr6_DFqjw4St_px4MnKmgxWb7_LLH2vNE',
    appId: '1:27538477845:ios:dd4f2e2df6bc34d5414f1c',
    messagingSenderId: '27538477845',
    projectId: 'barber-booking-app-2ad2b',
    storageBucket: 'barber-booking-app-2ad2b.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC593pQKjcrxY6wJbEe95LOwvrgGp0v4tU',
    appId: '1:27538477845:web:acb66f9e116c89b7414f1c',
    messagingSenderId: '27538477845',
    projectId: 'barber-booking-app-2ad2b',
    authDomain: 'barber-booking-app-2ad2b.firebaseapp.com',
    storageBucket: 'barber-booking-app-2ad2b.firebasestorage.app',
    measurementId: 'G-FSNFPK7T6Q',
  );
}
